set -x
#python hmmlearn.py mr-ud-train.conllu
#python hmmdecode.py raw_mr-ud-test.conllu
#python accuracyTest.py mr-ud-test.conllu
#python hmmlearn.py no_bokmaal-ud-train.conllu
#python hmmdecode.py raw_no_bokmaal-ud-test.conllu
#python accuracyTest.py no_bokmaal-ud-test.conllu
#python hmmlearn.py it_partut-ud-train.conllu
#python hmmdecode.py raw_it_partut-ud-test.conllu
#python accuracyTest.py it_partut-ud-test.conllu
#python hmmlearn.py la_ittb-ud-train.conllu
#python hmmdecode.py raw_la_ittb-ud-test.conllu
#python accuracyTest.py la_ittb-ud-test.conllu
#python hmmlearn.py da-ud-train.conllu
#python hmmdecode.py raw_da-ud-test.conllu
#python accuracyTest.py da-ud-test.conllu
#python hmmlearn.py hu-ud-train.conllu
#python hmmdecode.py raw_hu-ud-test.conllu
#python accuracyTest.py hu-ud-test.conllu
#python hmmlearn.py hi-ud-train.conllu
#python hmmdecode.py raw_hi-ud-test.conllu
#python accuracyTest.py hi-ud-test.conllu
#python hmmlearn.py grc_proiel-ud-train.conllu
#python hmmdecode.py raw_grc_proiel-ud-test.conllu
#python accuracyTest.py grc_proiel-ud-test.conllu
#python hmmlearn.py en-ud-train.conllu
#python hmmdecode.py raw_en-ud-test.conllu
#python accuracyTest.py en-ud-test.conllu
#python hmmlearn.py fr_partut-ud-train.conllu
#python hmmdecode.py raw_fr_partut-ud-test.conllu
#python accuracyTest.py fr_partut-ud-test.conllu
#python hmmlearn.py ar-ud-train.conllu
#python hmmdecode.py raw_ar-ud-test.conllu
#python accuracyTest.py ar-ud-test.conllu
#python hmmlearn.py lt-ud-train.conllu
#python hmmdecode.py raw_lt-ud-test.conllu
#python accuracyTest.py lt-ud-test.conllu
#python hmmlearn.py el-ud-train.conllu
#python hmmdecode.py raw_el-ud-test.conllu
#python accuracyTest.py el-ud-test.conllu
##python hmmlearn.py no_nynorsk-ud-train.conllu
#python hmmdecode.py raw_no_nynorsk-ud-test.conllu
#python accuracyTest.py no_nynorsk-ud-test.conllu
#python hmmlearn.py lv-ud-train.conllu
#python hmmdecode.py raw_lv-ud-test.conllu
#python accuracyTest.py lv-ud-test.conllu
python hmmlearn.py ga-ud-train.conllu
python hmmdecode.py raw_ga-ud-test.conllu
python accuracyTest.py ga-ud-test.conllu
python hmmlearn.py gl-ud-train.conllu
python hmmdecode.py raw_gl-ud-test.conllu
python accuracyTest.py gl-ud-test.conllu
python hmmlearn.py gl_treegal-ud-train.conllu
python hmmdecode.py raw_gl_treegal-ud-test.conllu
python accuracyTest.py gl_treegal-ud-test.conllu
python hmmlearn.py fr-ud-train.conllu
python hmmdecode.py raw_fr-ud-test.conllu
python accuracyTest.py fr-ud-test.conllu
python hmmlearn.py zh-ud-train.conllu
python hmmdecode.py raw_zh-ud-test.conllu
python accuracyTest.py zh-ud-test.conllu
python hmmlearn.py ca_ancora-ud-train.conllu
python hmmdecode.py raw_ca_ancora-ud-test.conllu
python accuracyTest.py ca_ancora-ud-test.conllu
python hmmlearn.py cop-ud-train.conllu
python hmmdecode.py raw_cop-ud-test.conllu
python accuracyTest.py cop-ud-test.conllu
python hmmlearn.py fi_ftb-ud-train.conllu
python hmmdecode.py raw_fi_ftb-ud-test.conllu
python accuracyTest.py fi_ftb-ud-test.conllu
python hmmlearn.py id-ud-train.conllu
python hmmdecode.py raw_id-ud-test.conllu
python accuracyTest.py id-ud-test.conllu
python hmmlearn.py en_partut-ud-train.conllu
python hmmdecode.py raw_en_partut-ud-test.conllu
python accuracyTest.py en_partut-ud-test.conllu
python hmmlearn.py nl-ud-train.conllu
python hmmdecode.py raw_nl-ud-test.conllu
python accuracyTest.py nl-ud-test.conllu
python hmmlearn.py fi-ud-train.conllu
python hmmdecode.py raw_fi-ud-test.conllu
python accuracyTest.py fi-ud-test.conllu
python hmmlearn.py et-ud-train.conllu
python hmmdecode.py raw_et-ud-test.conllu
python accuracyTest.py et-ud-test.conllu
python hmmlearn.py hr-ud-train.conllu
python hmmdecode.py raw_hr-ud-test.conllu
python accuracyTest.py hr-ud-test.conllu
python hmmlearn.py la_proiel-ud-train.conllu
python hmmdecode.py raw_la_proiel-ud-test.conllu
python accuracyTest.py la_proiel-ud-test.conllu
python hmmlearn.py fr_ftb-ud-train.conllu
python hmmdecode.py raw_fr_ftb-ud-test.conllu
python accuracyTest.py fr_ftb-ud-test.conllu
python hmmlearn.py de-ud-train.conllu
python hmmdecode.py raw_de-ud-test.conllu
python accuracyTest.py de-ud-test.conllu
python hmmlearn.py he-ud-train.conllu
python hmmdecode.py raw_he-ud-test.conllu
python accuracyTest.py he-ud-test.conllu
python hmmlearn.py cs_cltt-ud-train.conllu
python hmmdecode.py raw_cs_cltt-ud-test.conllu
python accuracyTest.py cs_cltt-ud-test.conllu
python hmmlearn.py it_postwita-ud-train.conllu
python hmmdecode.py raw_it_postwita-ud-test.conllu
python accuracyTest.py it_postwita-ud-test.conllu
python hmmlearn.py fr_sequoia-ud-train.conllu
python hmmdecode.py raw_fr_sequoia-ud-test.conllu
python accuracyTest.py fr_sequoia-ud-test.conllu
python hmmlearn.py got-ud-train.conllu
python hmmdecode.py raw_got-ud-test.conllu
python accuracyTest.py got-ud-test.conllu
python hmmlearn.py it-ud-train.conllu
python hmmdecode.py raw_it-ud-test.conllu
python accuracyTest.py it-ud-test.conllu
python hmmlearn.py ja-ud-train.conllu
python hmmdecode.py raw_ja-ud-test.conllu
python accuracyTest.py ja-ud-test.conllu
python hmmlearn.py cs_fictree-ud-train.conllu
python hmmdecode.py raw_cs_fictree-ud-test.conllu
python accuracyTest.py cs_fictree-ud-test.conllu
python hmmlearn.py sme-ud-train.conllu
python hmmdecode.py raw_sme-ud-test.conllu
python accuracyTest.py sme-ud-test.conllu
python hmmlearn.py la-ud-train.conllu
python hmmdecode.py raw_la-ud-test.conllu
python accuracyTest.py la-ud-test.conllu
python hmmlearn.py nl_lassysmall-ud-train.conllu
python hmmdecode.py raw_nl_lassysmall-ud-test.conllu
python accuracyTest.py nl_lassysmall-ud-test.conllu
python hmmlearn.py bg-ud-train.conllu
python hmmdecode.py raw_bg-ud-test.conllu
python accuracyTest.py bg-ud-test.conllu
python hmmlearn.py cs_cac-ud-train.conllu
python hmmdecode.py raw_cs_cac-ud-test.conllu
python accuracyTest.py cs_cac-ud-test.conllu
python hmmlearn.py ko-ud-train.conllu
python hmmdecode.py raw_ko-ud-test.conllu
python accuracyTest.py ko-ud-test.conllu
python hmmlearn.py ar_nyuad-ud-train.conllu
python hmmdecode.py raw_ar_nyuad-ud-test.conllu
python accuracyTest.py ar_nyuad-ud-test.conllu
python hmmlearn.py grc-ud-train.conllu
python hmmdecode.py raw_grc-ud-test.conllu
python accuracyTest.py grc-ud-test.conllu
python hmmlearn.py en_lines-ud-train.conllu
python hmmdecode.py raw_en_lines-ud-test.conllu
python accuracyTest.py en_lines-ud-test.conllu
python hmmlearn.py be-ud-train.conllu
python hmmdecode.py raw_be-ud-test.conllu
python accuracyTest.py be-ud-test.conllu
python hmmlearn.py eu-ud-train.conllu
python hmmdecode.py raw_eu-ud-test.conllu
python accuracyTest.py eu-ud-test.conllu
python hmmlearn.py af-ud-train.conllu
python hmmdecode.py raw_af-ud-test.conllu
python accuracyTest.py af-ud-test.conllu

